### PR TITLE
Fix a vue 3.1 incompatibility.

### LINKED ISSUE #5: Error Cannot read property 'emit' of undefined on Blank demo project
I tried to install it in a fresh install from vue-cli:

modiefied the App.vue from the example to:

```
<template>
  <div id="App">
    <v-grid
      theme="compact"
      :source="rows"
      :columns="columns"
    ></v-grid>
  </div>
</template>
 
<script>
import VGrid from "@revolist/vue3-datagrid";
export default {
  name: "App",
  data() {
    return {
      columns: [{ prop: "name" }, { prop: "details" }],
      rows: [{
        name: "1",
        details: "Item 1",
      }]
    };
  },
  components: {
    VGrid,
  },
};
</script>
```

but getting this error:

```
Uncaught TypeError: Cannot read property 'emit' of undefined
    at HTMLElement.columnChanged (vgrid.js?675a:1)
    at HTMLElement.connectedCallback (vgrid.js?675a:1)
    at HTMLElement.connectedCallback (vgrid.js?675a:1)
    at insert (runtime-dom.esm-bundler.js?830f:9)
    at mountElement (runtime-core.esm-bundler.js?5c40:4822)
    at processElement (runtime-core.esm-bundler.js?5c40:4754)
    at patch (runtime-core.esm-bundler.js?5c40:4670)
    at componentEffect (runtime-core.esm-bundler.js?5c40:5208)
    at reactiveEffect (reactivity.esm-bundler.js?a1e9:42)
    at effect (reactivity.esm-bundler.js?a1e9:17)
columnChanged @ vgrid.js?675a:1
connectedCallback @ vgrid.js?675a:1
connectedCallback @ vgrid.js?675a:1
insert @ runtime-dom.esm-bundler.js?830f:9
mountElement @ runtime-core.esm-bundler.js?5c40:4822
processElement @ runtime-core.esm-bundler.js?5c40:4754
patch @ runtime-core.esm-bundler.js?5c40:4670
componentEffect @ runtime-core.esm-bundler.js?5c40:5208
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5154
mountComponent @ runtime-core.esm-bundler.js?5c40:5113
processComponent @ runtime-core.esm-bundler.js?5c40:5071
patch @ runtime-core.esm-bundler.js?5c40:4673
componentEffect @ runtime-core.esm-bundler.js?5c40:5274
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
callWithErrorHandling @ runtime-core.esm-bundler.js?5c40:154
flushJobs @ runtime-core.esm-bundler.js?5c40:386
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js?5c40:286
queueJob @ runtime-core.esm-bundler.js?5c40:280
run @ reactivity.esm-bundler.js?a1e9:183
trigger @ reactivity.esm-bundler.js?a1e9:189
set value @ reactivity.esm-bundler.js?a1e9:764
eval @ runtime-core.esm-bundler.js?5c40:2575
Promise.then (async)
setup @ runtime-core.esm-bundler.js?5c40:2574
callWithErrorHandling @ runtime-core.esm-bundler.js?5c40:154
setupStatefulComponent @ runtime-core.esm-bundler.js?5c40:7131
setupComponent @ runtime-core.esm-bundler.js?5c40:7087
mountComponent @ runtime-core.esm-bundler.js?5c40:5096
processComponent @ runtime-core.esm-bundler.js?5c40:5071
patch @ runtime-core.esm-bundler.js?5c40:4673
mountChildren @ runtime-core.esm-bundler.js?5c40:4861
mountElement @ runtime-core.esm-bundler.js?5c40:4782
processElement @ runtime-core.esm-bundler.js?5c40:4754
patch @ runtime-core.esm-bundler.js?5c40:4670
componentEffect @ runtime-core.esm-bundler.js?5c40:5208
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5154
mountComponent @ runtime-core.esm-bundler.js?5c40:5113
processComponent @ runtime-core.esm-bundler.js?5c40:5071
patch @ runtime-core.esm-bundler.js?5c40:4673
render @ runtime-core.esm-bundler.js?5c40:5791
mount @ runtime-core.esm-bundler.js?5c40:4081
app.mount @ runtime-dom.esm-bundler.js?830f:1319
eval @ main.js?56d7:4
./src/main.js @ app.js:1009
__webpack_require__ @ app.js:849
fn @ app.js:151
1 @ app.js:1022
__webpack_require__ @ app.js:849
checkDeferredModules @ app.js:46
(anonymous) @ app.js:925
(anonymous) @ app.js:928
vgrid.js?675a:1 TypeError: Cannot read property 'registerElement' of undefined
    at registerElement (vgrid.js?675a:1)
    at ref (vgrid.js?675a:1)
    at D (vgrid.js?675a:1)
    at I (vgrid.js?675a:1)
    at H (vgrid.js?675a:1)
    at H (vgrid.js?675a:1)
    at H (vgrid.js?675a:1)
    at B (vgrid.js?675a:1)
    at G (vgrid.js?675a:1)
    at Q (vgrid.js?675a:1) <revo-grid class grid-uuid=​"1624786465197-rvgrid" theme=​"compact" row-class>​</revo-grid>​
      

      flex
    
xe @ vgrid.js?675a:1
oe @ vgrid.js?675a:1
ie @ vgrid.js?675a:1
eval @ vgrid.js?675a:1
ce @ vgrid.js?675a:1
ne @ vgrid.js?675a:1
r @ vgrid.js?675a:1
Re @ vgrid.js?675a:1
ze @ vgrid.js?675a:1
requestAnimationFrame (async)
raf @ vgrid.js?675a:1
eval @ vgrid.js?675a:1
re @ vgrid.js?675a:1
o @ vgrid.js?675a:1
de @ vgrid.js?675a:1
eval @ vgrid.js?675a:1
connectedCallback @ vgrid.js?675a:1
insert @ runtime-dom.esm-bundler.js?830f:9
mountElement @ runtime-core.esm-bundler.js?5c40:4822
processElement @ runtime-core.esm-bundler.js?5c40:4754
patch @ runtime-core.esm-bundler.js?5c40:4670
componentEffect @ runtime-core.esm-bundler.js?5c40:5208
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5154
mountComponent @ runtime-core.esm-bundler.js?5c40:5113
processComponent @ runtime-core.esm-bundler.js?5c40:5071
patch @ runtime-core.esm-bundler.js?5c40:4673
componentEffect @ runtime-core.esm-bundler.js?5c40:5274
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
callWithErrorHandling @ runtime-core.esm-bundler.js?5c40:154
flushJobs @ runtime-core.esm-bundler.js?5c40:386
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js?5c40:286
queueJob @ runtime-core.esm-bundler.js?5c40:280
run @ reactivity.esm-bundler.js?a1e9:183
trigger @ reactivity.esm-bundler.js?a1e9:189
set value @ reactivity.esm-bundler.js?a1e9:764
eval @ runtime-core.esm-bundler.js?5c40:2575
Promise.then (async)
setup @ runtime-core.esm-bundler.js?5c40:2574
callWithErrorHandling @ runtime-core.esm-bundler.js?5c40:154
setupStatefulComponent @ runtime-core.esm-bundler.js?5c40:7131
setupComponent @ runtime-core.esm-bundler.js?5c40:7087
mountComponent @ runtime-core.esm-bundler.js?5c40:5096
processComponent @ runtime-core.esm-bundler.js?5c40:5071
patch @ runtime-core.esm-bundler.js?5c40:4673
mountChildren @ runtime-core.esm-bundler.js?5c40:4861
mountElement @ runtime-core.esm-bundler.js?5c40:4782
processElement @ runtime-core.esm-bundler.js?5c40:4754
patch @ runtime-core.esm-bundler.js?5c40:4670
componentEffect @ runtime-core.esm-bundler.js?5c40:5208
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5154
mountComponent @ runtime-core.esm-bundler.js?5c40:5113
processComponent @ runtime-core.esm-bundler.js?5c40:5071
patch @ runtime-core.esm-bundler.js?5c40:4673
render @ runtime-core.esm-bundler.js?5c40:5791
mount @ runtime-core.esm-bundler.js?5c40:4081
app.mount @ runtime-dom.esm-bundler.js?830f:1319
eval @ main.js?56d7:4
./src/main.js @ app.js:1009
__webpack_require__ @ app.js:849
fn @ app.js:151
1 @ app.js:1022
__webpack_require__ @ app.js:849
checkDeferredModules @ app.js:46
(anonymous) @ app.js:925
(anonymous) @ app.js:928
```

my package.json : 

```
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@revolist/vue3-datagrid": "^3.0.52",
    "core-js": "^3.6.5",
    "vue": "^3.0.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```

Just a blank project.

### PR DESCRIPTION
**Pull request by michaelglas**
This fixes #5

### CODE REVIEW

**Comment by wglas85** [comment]
Thanks for your proposition, I just learned about ES's Symbol() and applied a likewise patch.
@odex21  Do you have an idea how to endorse a new release of vue3-datagrid?

**Comment by odex21** [comment]
I haven't seen the maintainer for a while, and I don't know what he has in mind, but I am currently hoping that some of the plugins and plugin api's can be enhanced.

In my own project, I use revogrid directly, because using it in vue is as simple as writing a wrapper.

Then because I used vite to develop vue3, vue-grid was also packaged with vite, but not actually packaged, my project was monorepo and vite linked directly to "vue-grid/src/index.ts"

**Comment by revolist** [comment]
@odex21 , @wglas85 , @michaelglas ty for the discussion.
Merged to master.
There is a small problem the part you've updated is auto-generated and need to check stenciljs generator for it.

Currently, we are focused on the product that is based on the grid system, this project is maintaining but not that much as initially. 

Going to provide new version of grid system together with some advanced samples when we release 4+ version.

**Comment by wglas85** [comment]
> @odex21 , @wglas85 , @michaelglas ty for the discussion.
> Merged to master.
> There is a small problem the part you've updated is auto-generated and need to check stenciljs generator for it.

Thanks for merging ;-)

> Currently, we are focused on the product that is based on the grid system, this project is maintaining but not that much as initially.
> 
> Going to provide new version of grid system together with some advanced samples when we release 4+ version.

Could you please give us some insights on the new grid system? We really like to have an EXCEL-like datagrid for vue3 and we are willing to participate, because we intend to introduce this component in a larger project with timeframe of several years.

Will there be a vue3-datagrid in version 4 with a similar interface or do we have to expect breaking changes?

  TIA and best regards, Wolfgang

**Comment by revolist** [comment]
Hello @wglas85 
Sorry for always delayed answers. 
There are no plans for breaking changes.

Main plan is to build more documentation, expose more methods and data for plugin support. Provide more information on building plugins without changing grid's code itself.

Also we want to introduce something as Premium plan with advances documentation, new plugins and support.

**Comment by wglas85** [comment]
JFYI, we refrained from using Revogrid because of some technical issues and because of the ridiculous non-responsiveness on Pull Requests. No matter how you intend to design your Premium plan, I wish you all the best for it.

**Comment by revolist** [comment]
Hello @wglas85 
Sorry to hear that you've lost interest in our product.

Also I am very sorry about responsiveness of our team, you should understand that product is open source and we have no profit of it, so we answer only if we have some free time (which is rare).

For what is worse we believed that community would be interested in creation of new features and organic grow but for now we see only consumer interest. At this moment we are going to open a Sponsorship program to see if anyone is going to be interested in allocated resource for documentation and support, if this goes well community will show how interested it is.

Our team at this time is focused on developing new product based on the revo-grid, which is going to show full potential of the grid and it's core and provide new practices and techniques at this area and leads to updates mentioned in previous message.

@wglas85 again we are very sorry to loose you, you were a huge part of our community.

Thanks for your support,

Best,
Revolist

**Pull request merged**
